version: '3.8'

services:
  # DevOps Monitor UI - Development mode with hot reloading
  devops-monitor-ui:
    build:
      context: ./ui-next
      dockerfile: Dockerfile.dev
    container_name: devops-monitor-ui-dev
    ports:
      - "4000:3000"
    volumes:
      - ./ui-next:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus
      - grafana
      - loki

networks:
  monitoring:
    external: true
